### ISSUE TITLE
Error in Raster while running replay

### ISSUE THREAD

**Issue by ranitdas2** [JeffersonLab/HallA-APEX-Online#45]
Error Message: Warning in <THaRaster("FbusRrb.Raster2")::Decode()>: Number of fired Channels out of range. Setting beam position to nominal values

**Comment by jbane11** [comment]
This is caused by the Fast bus Beamline module added by the replay. We no longer have beamline information in Fbus anymore. So I had commented those sections out some time ago. It was commit 66a9014bb1753927b7f1db69773fa7d23ab12b10.  I guess somehow those changes got revert by someone else.

**Comment by jbane11** [comment]
Fixed in replay still needs to be adjusted in odef

**Comment by jbane11** [comment]
Fixed in odef now, also
