### ISSUE TITLE
SciFi replay issue

### ISSUE THREAD

**Issue by jbane11** [JeffersonLab/HallA-APEX-Online#9]
For some reason, the SciFi classes will look for a module that it can not find, on every event!!! Either there is a mistake in the detmap, or the formulation of the decode algorithm. I would first suggest confirming the correct detmap, and confirming the information is in the data stream.

**Comment by johnaldhino** [comment]
Is this for left or right HRS replays?

**Comment by jbane11** [comment]
This was on a RHRS replay

**Comment by johnaldhino** [comment]
Thanks, I;ll try and have a look at it. I'm pretty sure the mapping is correct as I've adjusted the DAC levels and seen the changes in the output for SciFi (changing pedestal levels).

**Comment by johnaldhino** [comment]
I added one line to db_cratemap.dat to add the extra slot which was being complained about and it now works I think.
